2023-02-25 15:54:06.969769	folder path: experiments/mnist_longT/sde-flow/mnistsgm_const/mnist-True-False-128-0.0001-100000
2023-02-25 15:54:06.972134	Namespace(dataset='mnist', dataroot='~/.datasets', saveroot='experiments/mnist_longT', expname='mnistsgm_const', print_every=2000, sample_every=2000, checkpoint_every=2000, num_steps=1000, T0=10.0, vtype='rademacher', batch_size=128, test_batch_size=256, lr=0.0001, num_iterations=100000, real=True, debias=False)
True
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs9732c21fc99396d700086657'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs7f87637d08e7087100086656'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsf1f41b9a4831912000086658'
OSError: [Errno 16] Device or resource busy: '.nfs1591d049f5aab90600086659'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsb44c36a42379bbf90008665a'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs200438e2901a24320008665b'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsb21ede2304438dcb0008665d'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfsd6202cda2580efae0008665c'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0d3a4c7dd4831a9e0008665e'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs8dbdd6f3f86e663b0008665f'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs79ea1aac6b31224b00086660'
Traceback (most recent call last):
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bjzhang_umass_edu/.conda/envs/tapsgm_gpu/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs6fa3a4b71010a2a300086661'
2023-02-25 15:56:29.304345	Iteration 100000 	BPD 1.3378088474273682
2023-02-25 15:56:29.312425	Finished training
